//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medications.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medications.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackArrow {
            get {
                object obj = ResourceManager.GetObject("BackArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acetaminophen/APAP (Tylenol/APAP)
        ///acetaminophen/codeine (Tylenol #3)
        ///albuterol (proair, proventil)
        ///alendronate (fosamax)
        ///allopurinol
        ///alprazolam (xanax)
        ///aluminum hydroxide, magnesium hydroxide (maalox)
        ///amitriptyline (elavil)
        ///amlodipine (norvasc)
        ///amoxicillin (amoxil)
        ///aripiprazole (abilify)
        ///artificial tears (hypo tears, genteal, culluvisc, lacri-lub, nature&apos;s tears, refresh)
        ///ascorbic acid (vitamin C)
        ///aspirin + ER dipyridamole (aggrenox)
        ///aspirin/acetylsalicylic acid (ASA)
        ///atenolol (tenormin)
        ///ato [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Drugs {
            get {
                return ResourceManager.GetString("Drugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NON-NARCOTIC ANALGESICS
        ///NARCOTIC ANALGESICS
        ///BRONCHODILATORS
        ///BONE RESORPTION INHIBITORS
        ///ANTIGOUT
        ///ANTIANXIETY
        ///ANTACIDS / ANTI-FLATULANTS
        ///ANTIDEPRESSANTS
        ///ANTI-HYPERTENSIVES, CALCIUM CHANNEL BLOCKERS (ALSO ANTIANGINAL)
        ///ANTIBIOTIC, anti-infective
        ///ANTIPSYCHOTICS
        ///OPTHALMICS (MOISTURIZER)
        ///VITAMINS
        ///ANTICOAGULANTS
        ///NONSTERIODAL ANTI-INFLAMMATORY ANALGESICS
        ///ANTI-HYPERTENSIVES, BETA-BLOCKERS
        ///ANTIHYPERLIPIDEMIC
        ///SKELETAL MUSCLE RELAXANT
        ///OPTHALMICS (ANTI-GLAUCOMA)
        ///OPTHALMICS (ANTI-GLAUCOMA)
        ///LAXATIVES /  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrugUses {
            get {
                return ResourceManager.GetString("DrugUses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LabValuesCat {
            get {
                object obj = ResourceManager.GetObject("LabValuesCat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoserDog {
            get {
                object obj = ResourceManager.GetObject("LoserDog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat01 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat02 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat03 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat04 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat05 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat06 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat07 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat08 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat09 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat10 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat11 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat12 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat13 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat14 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat15 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat16 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat17 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat18 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat19 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode1Cat20 {
            get {
                object obj = ResourceManager.GetObject("Mode1Cat20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat01 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat02 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat03 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat04 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat05 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat06 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat07 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat08 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat09 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat10 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat11 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat12 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat13 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat14 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat15 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat16 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat17 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat18 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat19 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode2Cat20 {
            get {
                object obj = ResourceManager.GetObject("Mode2Cat20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat01 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat02 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat03 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat04 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat05 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat06 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat07 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat08 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat09 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat10 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat11 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat12 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat13 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat14 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat15 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat16 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat17 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat18 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat19 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mode3Cat20 {
            get {
                object obj = ResourceManager.GetObject("Mode3Cat20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Next {
            get {
                object obj = ResourceManager.GetObject("Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nausea, Abdominal Pain, Anorexia
        ///Constipation, N/V, Sedation, Respiratory Depression
        ///Nervousness, Restlessness, Tremor
        ///Weakness, Musculoskeletal Pain
        ///N/V, Drowsiness
        ///Drowsiness, Confusion, Dizziness, Dry Mouth
        ///Constipation, Diarrhea, Belching, Flatulence
        ///Dizziness, Drowsiness, Dry Mouth, Insomnia, Tremor
        ///Hypotension, Brady/Tachycardia, Headache, N/V, Dysrhythmias, Peripheral Edema
        ///N/V, Diarrhea
        ///Extrapyramidal Symptoms, Dry Mouth &amp; Eyes, Blurred Vision, Constipation
        ///Altered Taste, Photophobia
        ///Nau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SideEffects {
            get {
                return ResourceManager.GetString("SideEffects", resourceCulture);
            }
        }
    }
}
